version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - NODE_ENV=development
      - UPLOAD_DIR=/app/uploads
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./uploads:/app/uploads
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
  worker:
    build: ./backend
    command: npm run worker
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - NODE_ENV=development
      - UPLOAD_DIR=/app/uploads
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./uploads:/app/uploads
  cleanup:
    build: ./backend
    command: npm run cleanup
    depends_on:
      - redis
    environment:
      - NODE_ENV=development
      - UPLOAD_DIR=/app/uploads
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./uploads:/app/uploads
volumes:
  uploads: