services:
  - type: web
    name: photo-collage-backend
    env: docker
    plan: free
    dockerfilePath: backend/Dockerfile
    region: oregon

  - type: web
    name: photo-collage-frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: frontend/build
    region: oregon
    buildFilter:
      paths:
        - frontend/**
