services:
  - type: web
    name: photo-collage-backend
    env: docker
    plan: free
    dockerfilePath: backend/Dockerfile
    region: oregon
    repo: https://github.com/phuocly789/FullStack-Online-Photo-Collage-Tool
    branch: main
    envVars:
      - key: PORT
        value: 5000

  - type: web
    name: photo-collage-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    region: oregon
    repo: https://github.com/phuocly789/FullStack-Online-Photo-Collage-Tool
    branch: main
    envVars:
      - key: REACT_APP_API_URL
        value: https://photo-collage-backend.onrender.com
    buildFilter:
      paths:
        - frontend/**